### PR TITLE
Feature/company portal

### PR DESCRIPTION
**Pull request by Wmaxlees**
Basic company portal with a list of all prototypes for companies

### CODE REVIEW

**Comment by robfitzgerald** [comment]
looks good.  doesn't have the unit tests, but, i'm ok with just merging it. :+1:

**Comment by robfitzgerald** [comment]
i just noticed that all changes to feature/prototype-CRUD are covered by this branch.  should we delete that branch and only worry about merging this one?  https://github.com/amc-ucdenver/website/compare/feature/company-portal...feature/prototype-CRUD

**Comment by robfitzgerald** [comment]
but if that's the case, then i'd say let's
1. delete feature/prototype-CRUD
2. fix the PUT on this branch
3. merge.

**Comment by Wmaxlees** [comment]
I'm fine with that if you are. It'll probably make it easier for me. I pulled the previous branch into this branch just to see if they worked together.

**Comment by Wmaxlees** [comment]
Okay! I think this is all good now. I fixed the PUT so that it only updates fields that actually have values in them and there are now unit tests for both the factory and the controller. @robfitzgerald, if you approve, I'll merge.

**Comment by robfitzgerald** [comment]
There is a simpler, more js way to do this without checking typeof, but I'm sure this works too. I'll try and show an example some time. :+1: :-)

**Pull request merged**
