### PR TITLE
rework of install/run scripts and reduced package.json file count to …

### PR DESCRIPTION
**Pull request by robfitzgerald**
see README.md for new install/run instructions
or...read this!
pull this branch down fresh and then run
`npm install`
then
`npm start`
on a linux machine.  chances are, it will work.
just a little cleanup so we have 1 package.json file for all dependencies in npm, and we don't need all the shell files.

### CODE REVIEW

**Comment by Wmaxlees** [comment]
I like it. Does karma still work with the dependencies installed in the src/node_modules folder now, though?

**Comment by robfitzgerald** [comment]
It should, right? No directory structure changes, and all I've done is made node modules available to both directories, so I've expanded rather than restricted the availability of modules. I'll have to give it a run to see though, I didn't think of that.

**Comment by Wmaxlees** [comment]
I just tested. The site still works okay. The testing does not, though.

**Comment by robfitzgerald** [comment]
@Wmaxlees try again?
i had to make sure i had no node_modules directories in src/ or test/
and then i realized when ngAnimate was added to the source, it wasn't also added to the acmApp-debug.js file which is used by karma.

**Pull request merged**
