### PR TITLE
Prototype CRUD working on server side

### PR DESCRIPTION
**Pull request by Wmaxlees**
Post is kinda weird. I'm not exactly sure how to send an array through Postman. But everything else I tested and it works.

### CODE REVIEW

**Comment by robfitzgerald** [comment]
hey, i did a put with a valid _id with the following json:
`{ "cost": 100.00 }`
and as i thought, it wiped out all of the properties besides indirectly accessed ones:

```
[
  {
    "_id": "559df2b1a78147ccc254d00c",
    "cost": 100,
    "expenses": [],
    "activities": [
      {
        "name": "mock interviews"
      },
      {
        "name": "watch a scrum meeting"
      }
    ]
  }
]
```

put should allow for a modification of a single property in an entity.  it could still check that the attribute is valid, but, it should only write in the ones passed in the body and leave the rest untouched.

**Comment by robfitzgerald** [comment]
everything else looks solid!

**Comment by Wmaxlees** [comment]
Good catch. I didn't even think to check that. I'll probably need to fix that on the officer PUT operation as well.

**Comment by robfitzgerald** [comment]
we can close this right?

**Pull request merged**
